#!/usr/bin/env php
<?php

require __DIR__ . "/../../autoload.php";

$time = microtime(1);
try {
    $app = new \ThreadUnit\ThreadUnit($argv);
    $exitCode = $app->run();
} catch (Exception $e) {
    echo $e->getMessage() . "\n";
    echo $e->getTraceAsString() . "\n";
    $exitCode = 1;
}

$total = (microtime(1) - $time);
echo "\nTotal time: ";
if ($total > 1) {
    echo round($total, 2) . "s\n";
} else {
    echo round($total * 1000, 2) . "ms\n";
}

exit($exitCode);