#!/usr/bin/env php
<?php

$composer = __DIR__ . "/../../autoload.php";
if (file_exists($composer)) {
    // composer version
    require $composer;
} else {
    // dev version
    spl_autoload_register(
        function ($class) {
            $class = str_replace("\\", "/", $class);
            $file = __DIR__ ."/lib/{$class}.php";
            if (file_exists($file)) {
                require $file;
            }
        }
    );
}

$time = microtime(1);
try {
    $app = new \ThreadUnit\ThreadUnit($argv);
    $exitCode = $app->run();
} catch (Exception $e) {
    echo $e->getMessage() . "\n";
    echo $e->getTraceAsString() . "\n";
    $exitCode = 1;
}

$total = (microtime(1) - $time);
echo "\nTotal time: ";
if ($total > 1) {
    echo round($total, 2) . "s\n";
} else {
    echo round($total * 1000, 2) . "ms\n";
}

exit($exitCode);